version: '3'

services:
  conversion-service:
    build:
      context: ./conversion-service
      dockerfile: Dockerfile
    volumes:
      - conversion_temp:/tmp/conversions
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    external: true  # This should match your n8n network in Coolify

volumes:
  conversion_temp:
